language: python
cache: pip
python:
  - '3.5'
  - 3.5-dev
  - '3.6'
  - 3.6-dev
  - nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libuv-dev
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: colemaclean
  password:
    secure: 0p6dJgRNPUPmXEuW3piVlTqlCusRVvILWslhaLBBNQk3jKFexpr9Jat17H6VUg+iGuLFKNlZh8BUGiOJHxADycOPA76Td9MvAlFz1QhS2CuDB8NYlpz7YsQnM92WTTAh3mW964I2mC6U5sxw0K9gV6XMVgQc5dzCYumqUyagV0s=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: cole/aiosmtplib
