dist: trusty
sudo: false
language: python
cache: pip
matrix:
  include:
    - python: '3.5.2'
      env: EVENT_LOOP=asyncio
    - python: '3.5'
      env: EVENT_LOOP=asyncio
    - python: 3.5-dev
      env: EVENT_LOOP=asyncio
    - python: '3.6'
      env: EVENT_LOOP=asyncio
    - python: 3.6-dev
      env: EVENT_LOOP=asyncio
    - python: nightly
      env: EVENT_LOOP=asyncio
    - python: pypy3
      env: EVENT_LOOP=asyncio
    - python: '3.5.2'
      env: EVENT_LOOP=uvloop
      addons:
        apt:
          packages:
            - libuv-dev
    - python: '3.5'
      env: EVENT_LOOP=uvloop
      addons:
        apt:
          packages:
            - libuv-dev
    - python: 3.5-dev
      env: EVENT_LOOP=uvloop
      addons:
        apt:
          packages:
            - libuv-dev
    - python: '3.6'
      env: EVENT_LOOP=uvloop
      addons:
        apt:
          packages:
            - libuv-dev
    - python: 3.6-dev
      env: EVENT_LOOP=uvloop
      addons:
        apt:
          packages:
            - libuv-dev
    - python: nightly
      env: EVENT_LOOP=uvloop
      addons:
        apt:
          packages:
            - libuv-dev
  fast_finish: true
  allow_failures:
    - python: pypy3
      env: EVENT_LOOP=asyncio
    - python: nightly
      env: EVENT_LOOP=asyncio
    - python: nightly
      env: EVENT_LOOP=uvloop
install:
  - pip install tox-travis pytest-travis-fold coveralls codecov
script: tox
deploy:
  provider: pypi
  user: colemaclean
  password:
    secure: 0p6dJgRNPUPmXEuW3piVlTqlCusRVvILWslhaLBBNQk3jKFexpr9Jat17H6VUg+iGuLFKNlZh8BUGiOJHxADycOPA76Td9MvAlFz1QhS2CuDB8NYlpz7YsQnM92WTTAh3mW964I2mC6U5sxw0K9gV6XMVgQc5dzCYumqUyagV0s=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: cole/aiosmtplib
after_success:
  - COVERALLS_PARALLEL=true coveralls
  - codecov
